name: build

on:
  pull_request:
    branches: [ dev, main ]
    paths:
      - "src/**"
      - "package.json"
      - "yarn.lock"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: "yarn.lock"

      - name: install deps
        run: yarn install --frozen-lockfile

      - name: build
        run: yarn build

      - name: upload dist
        uses: actions/upload-artifact@v4
        with:
          name: fe-dist
          path: dist
          if-no-files-found: ignore
